app/views/frontend.py
from flask import (Blueprint, request, redirect, url_for, render_template,
                   abort, flash, session)
from flask import current_app as app
from urllib.request import urlopen
from urllib.parse import urlencode
import codecs
import json
import string
import random
from app.models import *

string_domain = string.ascii_letters + string.digits


frontend = Blueprint('frontend', __name__)


@frontend.app_errorhandler(404)
def handle_404(err):
    return render_template('404.html'), 404


@frontend.app_errorhandler(413)
def handle_413(err):
    return render_template('413.html'), 413


@frontend.app_errorhandler(500)
def handle_500(err):
    return render_template('500.html'), 500


@frontend.route('/github')
def github():
    return redirect('https://github.com/erm/minibin', code=302)


@frontend.route('/api')
def api():
    return render_template('api.html')


@frontend.route('/search', defaults={'page': 1}, methods=['POST'])
@frontend.route('/page/<int:page>', methods=['POST', 'GET'])
def search(page):
    if request.method == 'POST':
        terms = request.form.get('terms')
        if not terms:
            flash("No search terms specified.")
        else:
            terms = str(terms)
            pastes = Paste.query.whoosh_search(terms,
                                               app.config['MAX_SEARCH_RESULTS']
                                               ).paginate(page,
                                                          10,
                                                          False).items
            return render_template('view_many_pastes.html',
                                   pastes=pastes,
                                   page=page)
    return redirect(url_for('frontend.index'))


@frontend.route('/recent', defaults={'page': 1})
@frontend.route('/page/<int:page>', methods=['POST', 'GET'])
def recent(page):
    pastes = Paste.query.order_by(Paste.created_on.desc()
                                  ).limit(app.config['MAX_RECENT_RESULTS']
                                          ).paginate(page, 10, False).items
    return render_template('view_many_pastes.html',
                           pastes=pastes,
                           page=page)


@frontend.route('/')
def index():
    return render_template('index.html')


@frontend.route('/new', methods=['POST'])
def create_paste():
    if request.method == 'POST':
        #  verify the recaptcha response
        api_request_data = urlencode({
            'secret': app.config['RECAPTCHA_PRIVATE_KEY'],
            'response': request.form.get('g-recaptcha-response')})
        api_request = urlopen(app.config['RECAPTCHA_VERIFY_URL'],
                              data=api_request_data.encode('utf-8'))
        reader = codecs.getreader('utf-8')
        #  check the api response for success (True) or failure (False)
        try:
            api_response = json.load(reader(api_request)).get('success')
        except URLError:  # i probably want to handle this differently later
            flash("There was an error with the captcha, try again later.")
            return redirect(url_for('frontend.index'))
        else:
            if not api_response:
                flash("Invalid captcha!")
                return redirect(url_for('frontend.index'))
            else:  # they passed the recaptcha, we can create the paste now
                content = request.form.get('content')
                if not content:
                    flash("No paste content detected.")
                    return redirect(url_for('frontend.index'))
                url_id = ''.join([random.choice(string_domain)
                                 for i in range(8)])
                paste = Paste(url_id,
                              request.form.get('title', None),
                              content,
                              request.form.get('password', None),
                              True)  # change later (public/prviate)
                db.session.add(paste)
                db.session.commit()
                flash("Successfully created new paste!")
                return redirect(url_for('frontend.view_paste', url_id=url_id))


@frontend.route('/p/<url_id>', methods=['GET'])
def view_paste(url_id):
    session.pop('_flashes', None)
    paste = Paste.query.filter_by(url_id=url_id).first()
    return render_template('view_paste.html', paste=paste)

app/templates/api.html
{% extends "base.html" %}
{% block content %}
<h3>Retrieve an individual paste</h3>
<blockquote>URL - http://minib.in/api/v1/paste/[url_id]
<h4>Example usage/output</h4>
<pre>
        user@localhost:~$ curl http://minib.in/api/v1/paste/c9SJEqPH

        {
            "content": "test",
            "date_created": "2015-02-02 06:26:57",
            "id": 1,
            "title": "a title lol"
        }
</pre>
</blockquote>
{% endblock content %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block head %}
  <title>minibin</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="author" content="">
  <meta content="text/html; charset=UTF-8" http-equiv="content-type" />
  <meta charset="utf-8">
  <script src="https://www.google.com/recaptcha/api.js" async defer></script>
  <style type="text/css">
    body {
      font-family:arial;
    }
    textarea {
        font-family: monospace;
        display: block;
        width:40.5em;
        overflow: auto;
        margin-bottom: 0.2em;
        min-height:20em;
    }
    #nav {
      margin-right:30px;
      margin-bottom:0.2em;
    }
    #nav a {
      text-decoration: none;
    }
    #search {
      float:right;
    }
    .paste_info {
      margin-bottom: 0.2em;
      width: 20em;
    }
  }
  </style>
</head>
  {% endblock %}
<body>


 {% block navbar %}
    {% include 'navbar.html' %}
  {% endblock %}
    {% for message in get_flashed_messages() %}
      <strong>Error:</strong> {{ message }}
    {% endfor %}
  {% block content %}
  {% endblock %}

</body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block content %}
<form action="{{ url_for('frontend.create_paste') }}" method="post">
    <textarea name="content"></textarea>
    <input class="paste_info" placeholder="title (optional)" name="title" type="text">
    <input class="paste_info" placeholder="password (optional)" name="password" type="text">
    <div class="g-recaptcha" data-sitekey="{{config['RECAPTCHA_PUBLIC_KEY']}}"></div>
    <button type="submit" value="submit" class="btn btn-default">submit</button>
</form>
{% endblock content %}

app/templates/navbar.html
<div id="nav">
<span style="font-weight:bold;font-size:1.5em">minib.in</span>
  <a href="{{ url_for('frontend.index') }}">[new]</a>
    <a href="{{ url_for('frontend.recent') }}">[recent]</a>
    <a href="{{ url_for('frontend.api') }}">[api]</a>
    <a href="https://github.com/erm/minibin">[about]</a>
<form action="{{ url_for('frontend.search') }}" , method="post" style="display:inline;">
      <input type="text"  name="terms" placeholder="Search">
    <button type="submit">Submit</button>
  </form>
</div>

app/templates/view_many_pastes.html
{% extends "base.html" %}
{% block content %}
    {% for paste in pastes %}
        {{ paste.created_on }}<br>
        <a href="{{ url_for('frontend.view_paste', url_id=paste.url_id) }}">
        {{ paste.content[30:] if paste.content|length > 150 else paste.content }}</a>
        <br>
        <br>
    {% endfor %}
    {% if pastes.has_prev %}
        <a href="{{ url_for('frontend.search', page=pastes.prev_num) }}"> Prev </a>
    {% endif %}
    {% if pastes.has_next %}
        <a href="{{ url_for('frontend.search', page=pastes.next_num) }}"> Next </a>
    {% endif %}
{% endblock content %}

app/templates/view_paste.html
{% extends "base.html" %}
{% block content %}
{{ paste.title }} {{ paste.date_created }}
<textarea name="content">{{ paste.content }}</textarea>
{% endblock content %}